version: '3.3'

services:
  database:
    container_name: storedb
    image: postgres:11.5
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=kvkstore
      - POSTGRES_USER=kvkstore
    ports:
      - 5434:5432